training:
  batch_size: 16
  n_epochs: 10  #number of training epochs - superceded by n_iters 
  n_iters: 11  #maximum number of training iterations - stops before n_epochs if needed
  snapshot_freq: 5 #frequency with which to save weights and sample from output
  snapshot_sampling: true 
  anneal_power: 2 
  log_all_sigmas: false

sampling:
  batch_size: 36  #number of samples to produce for sampling
  data_init: false
  step_lr: 0.0000016  #epsilon - step size for sampling during Langevin Dynamics
  n_steps_each: 25 #T - number of inner loop steps
  ckpt_id: 80000  
  final_only: true
  fid: false
  denoise: true #whether to add \sigma^2 * s_theta(x_T, \sigma_T) to the final output
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 8

#unused
fast_fid:
  batch_size: 1000
  num_samples: 1000
  step_lr: 0.0000009
  n_steps_each: 3
  begin_ckpt: 100000
  end_ckpt: 80000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 10
  end_ckpt: 100
  batch_size: 100

data:
  dataset: "RTM_N"
  image_size: 256
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: false
  num_workers: 8

model:
  ema: true #use an exponential moving avergae?
  ema_rate: 0.999 #m, for parameters: \theta^' = m*\theta^' + (1 - m)\theta_i
  spec_norm: false
  sigma_dist: rtm_dynamic #the progression of the sigma values
  num_classes: 20
  n_shots: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20, 50, 100, 175, 240]
  lambdas_list: [0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.045, 0.04, 0.035, 0.03, 0.025, 0.02, 0.015, 0.01, 0.005, 0.001]
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
